# Welcome to Jekyll!

text_color_theme: default #eg: default | dark | forest | ocean | chocolate | orange

## Base settings ##

# baseurl:
url: https://breuer.dev
title: breuer.dev
description: > #this means to ignore newlines until "nav_lists:"
    learning by doing

nav_lists:
    - title: blog
      url: /blog/
    - title: tools
      url: /tools/

paths:
    base: /
    home: /
    all: /all.html
    rss: /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: en
timezone: Europe/Berlin #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
    name: felix
    email: felix@breuer.dev
    # facebook:  #your Facebook username
    twitter: felix_breuer
    github: breuerfelix
    # googleplus:  #your Google+ username
    # weibo:  #your Weibo username
    # douban:  #your Douban username
    linkedin: felix-breuer-5b70b3179

## TOC
toc:
    # selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
disqus:
    # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
    clientID: 825db415b2ec7a891274
    clientSecret: 4204bbd65a8dc347d5f94b5f0f33dbf43543efdf
    repository: breuerfelix.github.io
    owner: breuerfelix
    admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - owner

## Google Analytics ##
ga_tracking_id: UA-117436835-1 #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
    # app_id:  #LeanCloud App id
    # app_key:  #LeanCloud App key
    # app_class:  #LeanCloud App class

# mathjax: true
# mathjax_autoNumber: true
# mermaid: true
# chart: true

## Paginate ##
paginate: 10
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: none

include:
    - projects
    - tools
    - blog

exclude:
    - README-*.md
    - README.md

## Plugins ##
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
    - jemoji

## Server ##
host: '127.0.0.1'
port: 4000
